name: "Deploy"

on:
  push:
    branches:
      - 'main'
    paths:
      - 'src/**'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID}}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy
        run: |
          az stack sub create \
            --name 'default' \
            --template-file ./src/main.bicep \
            --parameters ./src/parameters/main.bicepparam \
            --deny-settings-mode 'none' \
            --delete-all \
            --yes
