name: 'Deployment'

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "src/**"

env:
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_APPLICATION_ID: ${{ secrets.ARM_APPLICATION_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}

jobs:

  build:
    name: 'Build'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: .github/scripts/install.sh
      - name: Connect
        run: .github/scripts/connect.sh
      - name: Build
        run: .github/scripts/build.sh
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: template
          path: ./src/main.json

  validate:
    name: 'Validate'
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect
        run: .github/scripts/connect.sh
      - name: Download
        uses: actions/download-artifact@v2
        with:
          name: template
          path: ./src/main.json
      - name: Validate
        run: .github/scripts/validate.sh

  deploy:
    name: 'Deploy'
    runs-on: ubuntu-20.04
    needs: validate
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect
        run: .github/scripts/connect.sh
      - name: Download
        uses: actions/download-artifact@v2
        with:
          name: template
          path: ./src/main.json
      - name: Create
        run: .github/scripts/create.sh
